doctrine:
    orm:
        auto_generate_proxy_classes: false
        result_cache_driver:
            type: predis
            host: localhost
            port: 6379
        query_cache_driver:
            type: predis
            host: localhost
            port: 6379
        metadata_cache_driver:
            type: predis
            host: localhost
            port: 6379

services:
    doctrine.result_cache_provider:
        class: Symfony\Component\Cache\DoctrineProvider
        public: false
        arguments:
            - '@doctrine.result_cache_pool'
    doctrine.system_cache_provider:
        class: Symfony\Component\Cache\DoctrineProvider
        public: false
        arguments:
            - '@doctrine.system_cache_pool'

framework:
    cache:
        pools:
            doctrine.result_cache_pool:
                adapter: cache.app
            doctrine.system_cache_pool:
                adapter: cache.system
